// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(FPTContext))]
    [Migration("20250526085918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinessObjects.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1e0b9d2-a3f4-4e5d-b8c7-6d9e8f0a1b2c"),
                            Address = "Redmond, WA",
                            Country = "USA",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("d1a1b2c3-d4e5-6789-abcd-ef0123456789"),
                            Address = "Mountain View, CA",
                            Country = "USA",
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("BussinessObjects.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            Age = 30,
                            CompanyId = new Guid("c1e0b9d2-a3f4-4e5d-b8c7-6d9e8f0a1b2c"),
                            Name = "John Doe",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000002"),
                            Age = 28,
                            CompanyId = new Guid("c1e0b9d2-a3f4-4e5d-b8c7-6d9e8f0a1b2c"),
                            Name = "Jane Smith",
                            Position = "Project Manager"
                        });
                });

            modelBuilder.Entity("BussinessObjects.Models.Employee", b =>
                {
                    b.HasOne("BussinessObjects.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BussinessObjects.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
